// Initial Migration

exports.up = function(knex) {
    return knex.schema
        // Users
        .createTable('users', table  => {
            table.increments('id')
            table.uuid('uuid')
                .notNullable()
                .unique()
            table.string('email')
                .notNullable()
                .unique()
            table.string('password')
                .notNullable()
            table.string('first_name')
                .notNullable()
            table.string('last_name')
                .notNullable()
            table.string('avatar_url')
            table.string('degree')
            table.date('study_start')
            table.string('security_token')
                .notNullable()
            table.boolean('is_admin')
                .notNullable()
                .defaultTo(false)
            table.boolean('is_banned')
                .notNullable()
                .defaultTo(false)
            table.boolean('is_verified')
                .notNullable()
                .defaultTo(false)
            table.timestamps(true, true)
        })
        // Modules
        .createTable('modules', table => {
            table.increments('id')
            table.uuid('uuid')
                .notNullable()
                .unique()
            table.string('name')
            table.timestamps(true, true)
        })
        // Questions
        .createTable('questions', table => {
            table.increments('id')
            table.uuid('uuid')
                .notNullable()
                .unique()
            table.string('question')
                .notNullable()
            table.string('explanation')
            table.string('answer_a')
                .notNullable()
            table.string('answer_b')
                .notNullable()
            table.string('answer_c')
                .notNullable()
            table.string('answer_d')
                .notNullable()
            table.enu('correct_answer', ['A', 'B', 'C', 'D'], {
                useNative: true,
                enumName: 'answer_type'
            })
                .notNullable()
            table.integer('module')
                .references('id')
                .inTable('modules')
                .notNullable()
            table.integer('author')
                .references('id')
                .inTable('users')
                .notNullable()
            table.timestamps(true, true)
        })
        // Games
        .createTable('games', table => {
            table.increments('id')
            table.uuid('uuid')
                .notNullable()
                .unique()
            table.integer('turn')
                .notNullable()
                .defaultTo(0)
            table.integer('module')
                .references('id')
                .inTable('modules')
                .notNullable()
            table.integer('winner')
                .references('id')
                .inTable('users')
            table.integer('loser')
                .references('id')
                .inTable('users')
            table.integer('given_up_by')
                .references('id')
                .inTable('users')
            table.boolean('is_game_over')
                .defaultTo(0)
                .notNullable()
            table.integer('user_sent_by')
                .references('id')
                .inTable('users')
                .notNullable()
            table.integer('user_sent_to')
                .references('id')
                .inTable('users')
                .notNullable()
            table.integer('current_player')
                .references('id')
                .inTable('users')
                .notNullable()
            table.timestamps(true, true)
        })
        // Game Questions
        .createTable('game_questions', table => {
            table.increments('id')
            table.uuid('uuid')
                .notNullable()
                .unique()
            table.enu('user_a_answer', null, {
                useNative: true,
                existingType: true,
                enumName: 'answer_type'
            })
            table.enu('user_b_answer', null, {
                useNative: true,
                existingType: true,
                enumName: 'answer_type'
            })
            table.integer('game')
                .references('id')
                .inTable('games')
                .notNullable()
            table.integer('question')
                .references('id')
                .inTable('questions')
                .notNullable()
            table.boolean('is_played_by_user_a')
                .defaultTo(0)
            table.boolean('is_played_by_user_b')
                .defaultTo(0)
            table.timestamps(true, true)
        })
        // Friendships
        .createTable('friendships', table => {
            table.increments('id')
            table.uuid('uuid')
                .notNullable()
                .unique()
            table.integer('user_sent_by')
                .references('id')
                .inTable('users')
                .notNullable()
            table.integer('user_sent_to')
                .references('id')
                .inTable('users')
                .notNullable()
            table.timestamps(true, true)
        })
}

exports.down = function(knex) {
    return knex.schema
        .raw('DROP TYPE answer_type CASCADE')
        .raw('DROP TABLE users CASCADE')
        .raw('DROP TABLE modules CASCADE')
        .raw('DROP TABLE questions CASCADE')
        .raw('DROP TABLE games CASCADE')
        .raw('DROP TABLE game_questions CASCADE')
        .raw('DROP TABLE friendships CASCADE')
}
